packages:
  - apps/*
  - packages/*

allowBuilds:
  '@nestjs/core': false
  '@scarf/scarf': false

ignoredBuiltDependencies:
  - '@scarf/scarf'

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@nestjs/core'
