import {
  Archive,
  Award,
  Banknote,
  Building2,
  Castle,
  Church,
  Clapperboard,
  Coins,
  Drama,
  Film,
  Gavel,
  GraduationCap,
  Hospital,
  Landmark,
  LandmarkIcon,
  MapPin,
  Pill,
  Scale,
  School,
  Shield,
  Stethoscope,
  Store,
  Theater,
  TreePine,
  Trophy,
  University,
  Wine,
  type LucideIcon,
} from 'lucide-react-native';
import type { BuildingType } from '@figlolandia/game-core';

export const BUILDING_ICONS: Record<BuildingType, LucideIcon> = {
  nursery: School,
  kindergarten: School,
  school: GraduationCap,
  technical_school: University,
  high_school: University,
  university: University,
  pharmacy: Pill,
  clinic: Stethoscope,
  nursing_home: Hospital,
  medical_clinic: Hospital,
  hospital: Hospital,
  cemetery: Church,
  exchange_office: Banknote,
  auction_house: Award,
  bank: Landmark,
  stock_exchange: Scale,
  mint: Coins,
  city_archive: Archive,
  police_station: Shield,
  city_hall: LandmarkIcon,
  court: Gavel,
  town_hall: Castle,
  bar: Wine,
  park: TreePine,
  cinema: Film,
  theater: Drama,
  stadium: Trophy,
};

export const getBuildingIcon = (type: string): LucideIcon =>
  BUILDING_ICONS[type as BuildingType] ?? Building2;
